spring:
  application:
    name: SPRING-CLOUD-STREAM
  cloud:
    function:
      definition: logEventReceived;sensorEventProducer
    stream:
      bindings:
        logEventReceived-in-0: #a consumer
          destination: sensor_event_topic
          group: ${spring.application.name}
        sensorEventProducer-out-0: #a producer
          destination: sensor_event_topic

# https://www.vincenzoracca.com/en/blog/framework/spring/cloud-stream/

# spring.cloud.function.definition: logEventReceived;sensorEventProducer: This property defines the application functions that will be used by the Spring Cloud
# Stream framework. In this case, there are two functions: logEventReceived and sensorEventProducer.

# stream.bindings: This section defines the bindings for the functions, specifying the input and output destinations for messaging.

# logEventReceived-in-0: This declares an input binding for the logEventReceived function. It specifies that messages will be consumed from the 
# sensor_event_topic destination.

# sensorEventProducer-out-0: This declares an output binding for the sensorEventProducer function. It specifies that messages produced by this 
# function will be sent to the sensor_event_topic destination.

#    The spring.cloud.function.definition property is used to define the application functions annotated with @Bean.
#    The functions are separated by a semicolon.
#    The spring.cloud.stream.bindings property is used to declare for each producer/consumer its destination
#    (in this case it is the name of a Topic Kafka). The following naming convention is used:
#    for input bindings: <functionName> + -in- + <index>.
#    for output bindings: <functionName> + -out- + <index>. The index field is always 0 when we want to exploit the concept
#    of message groups.
#    The consumer logEventReceived, in addition to having the destination field, also has the group field indicating the
#    name of the Message Group.
#    Each consumer in the same Message Group, reads messages from a different partition, so that it shares messages with the other consumers, in a horizontal scaling manner.
